sudo: false
language: node_js
notifications:
  email: false
install: true

jobs:
  include:
    - stage: staging
      node_js: '10'
      if: branch = master AND tag IS blank
      script:
        - docker build -t allovince/certbot .
        - docker tag allovince/certbot allovince/certbot:staging
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/certbot:staging;
    - stage: docker release
      node_js: '10'
      if: tag IS present
      script:
        - docker build -t allovince/certbot .
        - docker tag allovince/certbot allovince/certbot:$TRAVIS_TAG
        - docker images
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        - docker push allovince/certbot:latest;
        - docker push allovince/certbot:$TRAVIS_TAG;

